### PR TITLE
Fixed input fields and container overlapping

### PR DESCRIPTION
**Pull request by Pl4gue**
#4 

-Added bottom padding to last input container, so that the footer buttons don't overlap the content of the last container

-Made all input fields to only number input

### CODE REVIEW

**Comment by idealadarsh** [comment]
@Pl4gue Can you attach a working build?  e.g. apk file

**Comment by Pl4gue** [comment]
Sure, you can find it at /app/build/outputs/apk/apk-debug.apk, working on all my Android devices.

**Comment by idealadarsh** [comment]
@Pl4gue Don't commit it, Please revert your last commit. 
I meant attach a working apk file here in this PR's conversation. So, I can check that before merging this pull request.

**Comment by Pl4gue** [comment]
@idealadarsh  I cannot attach it here, so I uploaded it:
https://files.fm/u/x7mmwwxx

**Comment by idealadarsh** [comment]
@Pl4gue You actually changed target sdk version and build tools version. And there are some merge conflicts as well.

**Pull request closed without merging**
